<a href="https://colab.research.google.com/github/tohnperfect/DWDM21/blob/main/Distance_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np # package สำหรับทำงานกับ ข้อมูลที่เป็นตัวเลข (อยู่ในรูปแบบ matrix)

# Numpy Array

## สร้าง numpy array (matrix) จาก list

In [ ]:
np_a = np.array([[1,2,3],[4,5,6]]) #สร้าง numpy array ที่มี 2 แถว 3 หลัก

In [ ]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np_a.shape

(2, 3)

In [ ]:
np_b = np.array([[1,4],[2,5],[3,6]])
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

### matrix transpose

In [ ]:
np_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## สร้าง matrix เริ่มต้น (zeros, ones)

In [ ]:
np_z = np.zeros((4,5))
np_z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np_o = np.ones((5,6))
np_o

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np_200 = 200 * np.ones((4,7))
np_200

array([[200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200., 200., 200.]])

## สร้าว matrix random

In [ ]:
np.random.randn(5,5) # random เลขมาจาก normal distribution ที่มี mu=0 std=1

array([[ 1.12568048, -0.11451459,  0.35358632,  0.61477583,  1.1989573 ],
       [ 1.76214619, -0.40878021, -0.26269636,  0.86096409,  0.29913134],
       [-0.15709792, -0.31976814, -0.07032593, -0.38881817,  0.04872013],
       [-1.17961641, -0.74285444,  0.56274378, -1.08757439, -0.19926645],
       [-0.36471014,  0.83321638, -1.62831772, -0.64446381,  0.05525063]])

In [ ]:
2+(5*np.random.randn(3,3)) # random เลขมาจาก normal distribution ที่มี mu=2 std=5

array([[ 6.46501999, 10.71857655,  1.97147266],
       [-1.01035674,  7.14537325,  8.45163089],
       [ 6.77246255,  4.95306354, -5.66076555]])

In [ ]:
np.random.randint(5,11,(4,5)) # random เลขจำนวนเต็ม ระหว่าง [5,11) ขนาด (4x5)

array([[ 9,  6, 10,  7,  7],
       [ 6,  7,  7, 10,  6],
       [ 7,  5,  8,  9,  8],
       [ 9,  5,  6,  9,  5]])